apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld1-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: helloworld1
  template:
    metadata:
      labels:
        app: helloworld1
    spec:
      containers:
      - name: k8s-demo
        image: odinxux/udemy_k8s:nodedemo
        ports:
        - name: nodejs-port
          containerPort: 3000
