apiVersion: v1
kind: Pod
metadata:
  name: nodehello
  labels:
    app: helloworld
spec:
  containers:
  - name: k8s-node
    image: odinxux/udemy_k8s:nodedemo
    ports:
    - name: nodejs-port
      containerPort: 3000
